version: '3.8'

services:
    mysql:
      build:
        context: ./mysql
      container_name: mysql    
      environment:
          MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
          MYSQL_DATABASE: ${MYSQL_DATABASE}
      healthcheck: 
          test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
          interval: 10s 
          retries: 5
          start_period: 30s
          timeout: 10s
      ports:
       - "3306:3306"
      volumes:
       - ./mysql_data:/var/lib/mysql
  
   
    fastapi:
       build:
         context: ./backend
       container_name: fastapi
       depends_on:
         mysql:
           condition: service_healthy
       ports:
        - "8000:8000"
volumes:
   mysql_data:    
     driver: local        

     