version: '3.8'

services:
   fastapi:
     build:
       context: ./
     container_name: fastapi
     ports: 
      - "8000:8000"
     networks:
     - external_network
networks:
  external_network:
    external: true

      